### ISSUE TITLE
nowにデプロイできない

### ISSUE THREAD

**Issue by Hykwtakumin** [Hykwtakumin/SFC-SFS-LINEbot#1]
手元でtscする分にはトランスパイルできるがデプロイ時にモジュールを解決できない模様
(`cheerio-httpcli`が見つからないと言われる)

**対応**
- yarnではなく全部npmでinstallしてみる
- そもそもcheerio使わない

**エラーコード**
> Your deployment's code and logs will be publicly accessible because you are subscribed to the OSS plan.
> NOTE: You can use `now --public` or upgrade your plan (https://zeit.co/account/plan) to skip this prompt
> Using Node.js 8.11.2 (default)
> https://sfc-sfs-linebot-xokxltkdls.now.sh [in clipboard] (sfo1) [4s]
> Synced 1 file (670B) [4s]
> Building…
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 6 main dependencies…
> ✓ Installed 87 modules [1s]
> ▲ npm run build
> 
> SFC-SFS-LINEbot@0.1.0 build /home/nowuser/src
> tsc
> 
> src/index.ts(3,26): error TS2307: Cannot find module 'cheerio-httpcli'.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! SFC-SFS-LINEbot@0.1.0 build: `tsc`
> npm ERR! Exit status 2
> npm ERR! 
> npm ERR! Failed at the SFC-SFS-LINEbot@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/nowuser/.npm/_logs/2018-06-28T00_12_02_513Z-debug.log
> Error! Build failed

**Comment by Hykwtakumin** [comment]
デプロイはできた!
make buildの処理をmake startに書くとコケるので別々に書く

**Comment by shokai** [comment]
package.jsonのengineでnodejsのバージョンが指定した方が良さそう
https://zeit.co/docs/deployment-types/node#custom-node.js-configuration

指定されていないせいで、nowが使うnodejsが定まらないのが怪しい気がする。
node 8〜10の間でコンパイルが必要なnpmが結構変わっているので
